### ISSUE TITLE
1+1=?

### ISSUE THREAD

**Issue by Wanqi-Wang** [pzhaonet/dph206-2020#1]

**Comment by jiaxuanPeng** [comment]
it's 2

**Comment by Bella-yijing** [comment]
2!!!!

**Comment by pzhaonet** [comment]
Good job, @Wanqi-Wang @jiaxuanPeng @Bella-yijing !

@Wanqi-Wang if you are satisfied with the answers given by @jiaxuanPeng or @Bella-yijing , you could give them a thumb, and then click the Close button below. Then this issue will disappear from the open issue list, and be moved to the closed ones.

If you are not satisfied, keep on discussing in this thread.

In principle, I will only answer the questions in the open issue list.
