### ISSUE TITLE
Problem if version control 

### ISSUE THREAD

**Issue by Wanqi-Wang** [pzhaonet/dph206-2020#13]
Hi, Dr. Zhao,

When i want to create a new repository with version control in R studio, it show me it:

fatal: repository 'DPH206 VC' does not exist

Do you know why it happens? Why cannot I create a new repository?

Wanqi

**Comment by pzhaonet** [comment]
You have to create a new repo on GitHub first, then create a new project in RStudio.

![](http://www.geo.uzh.ch/microsite/reproducible_research/post/rr-rstudio-git/img/RStudio-clone-git-project.gif)

More details can be found here:
- <http://www.geo.uzh.ch/microsite/reproducible_research/post/rr-rstudio-git/>

**Comment by Wanqi-Wang** [comment]
> You have to create a new repo on GitHub first, then create a new project in RStudio.
> 
> More details can be found here:
> 
> http://www.geo.uzh.ch/microsite/reproducible_research/post/rr-rstudio-git/

Got it! Thank you!
