### ISSUE TITLE
softwares use

### ISSUE THREAD

**Issue by Wanqi-Wang** [pzhaonet/dph206-2020#15]
Dr. Zhao, we shared our software use at let class. why not share yours. Besides R, what other software do you use? And the reason of why you use these software? What software did you learn at school in your age? And what are some you favorite R packages? Besides R, what software you think will be survival in future's world.

😺 

Thanks,
Wanqi

**Comment by pzhaonet** [comment]
See syllabus in the handbook. It is what I am going to talk next week.

**Comment by Wanqi-Wang** [comment]
> See syllabus in the handbook. It is what I am going to talk next week.

Thanks!
