### ISSUE TITLE
I cannot read the .csv document.

### ISSUE THREAD

**Issue by Bella-yijing** [pzhaonet/dph206-2020#20]
As the course, I save the ncov dataset as .csv file in the file named "dph206". Then, I enter the following code:

**Sys.getlocale()
Sys.setlocale('LC_CTYPE', 'Chinese')
df3 <- read.csv('dph206/ncov.csv')**

But it shows the error:
**Error in file(file, "rt") : 无法打开链结
此外: Warning message:
In file(file, "rt") :
  无法打开文件'dph206/ncov.csv': No such file or directory**

How should I do？

**Comment by pzhaonet** [comment]
I guess "dph206" is not a file, but a folder where your R project is located. If so, remove it from the file path:
 read.csv('ncov.csv')

**Comment by Bella-yijing** [comment]
##  Your suggestion seems to work, but still exist error.

1. 
I saved the ncov dataset as **.csv UTF-8 file**, Then I entered the following code:

**Sys.getlocale()
Sys.setlocale('LC_CTYPE', 'Chinese')
df3 <- read.csv('ncov.csv')**

But it showed the error:

**Error in make.names(col.names, unique = TRUE) : 多字节字符串1有错**
2. 
However, I ignored the error and proceed to enter the following code:

**df3 <- read.csv('ncov.csv', encoding = 'UTF-8')
df4 <- readr::read_csv('ncov.csv')
df4**

It worked, and the result showed the Chinese.
## I want to know why the code  **df3 <- read.csv('ncov.csv')** was wrong.

Thanks for your answer!!!

**Comment by Wanqi-Wang** [comment]
seems that your system already in Chinese..

**Comment by pzhaonet** [comment]
@Bella-yijing You have to use `fileEncoding `:

```
read.csv('ncov.csv', fileEncoding = 'UTF-8')
```

It should work well, but I cannot promise. I don't quite process Chinese characters. `readr::read_csv()` is a safer way from my point of view.

To find the difference between `encoding` and `fileEncoding`, see the help document.
