### ISSUE TITLE
Why cannot i see anthing at viewer when i use R markdown

### ISSUE THREAD

**Issue by Wanqi-Wang** [pzhaonet/dph206-2020#21]
When I write markdown, the viewer window in interface is empty, why does it happen?

**Comment by pzhaonet** [comment]
Markdown is not rendered in the view window. The view window is for something else. We will learn it later.

**Comment by Wanqi-Wang** [comment]
> Markdown is not rendered in the view window. The view window is for something else. We will learn it later.

Great, thanks, do you know how to preview Markdown?

**Comment by pzhaonet** [comment]
@Wanqi-Wang using the xaringan package, you can preview it in the View window. Remember this question in our next seminar and I will show you how.
