### ISSUE TITLE
Why the code cannot work as that in Handbook?

### ISSUE THREAD

**Issue by Bella-yijing** [pzhaonet/dph206-2020#4]
I input the codes in Typora and click the </> button, but nothing happen in these three codes:
PM~2.5~
R^2^
$E = mc^2$
What is the problem?

**Comment by pzhaonet** [comment]
See the [Typora manual](https://support.typora.io/Math/).

Briefly speaking, you have to switch them on in Preference.

![](https://support.typora.io/media/math/Snip20180818_2.png)

**Comment by Bella-yijing** [comment]
Thanks!!!!
