### ISSUE TITLE
How to insert an image?

### ISSUE THREAD

**Issue by Bella-yijing** [pzhaonet/dph206-2020#5]
The code is ![](image) , but I still don't understand how to insert an image? 
1. I opened the file and exported an image, it did not work.
2. I coped and pasted an image from a website into [] and (), neither did it work.

**Comment by pzhaonet** [comment]
See the [Typora manual](https://support.typora.io/Images/#how-to-insert-images-in-typora).

**Comment by Bella-yijing** [comment]
Thanks! I think ![alt]( ) is useful.
