### ISSUE TITLE
The problem about practice in Github

### ISSUE THREAD

**Issue by Bella-yijing** [pzhaonet/dph206-2020#6]
**Why the syntaxes have no change:** 

- PM~2.5~ 

- m^3^

**Comment by Wanqi-Wang** [comment]
```{r}
PM~2.5~
R^3^
```

**Comment by pzhaonet** [comment]
Because they are no basic markdown. They are supported by Typora, not by GitHub. A universal one is:

```
PM<sub>2.5</sub>
m<sup>3</sup>
```

PM<sub>2.5</sub>
m<sup>3</sup>
