### ISSUE TITLE
Interesting emoji function in github!

### ISSUE THREAD

**Issue by Wanqi-Wang** [pzhaonet/dph206-2020#7]
:+1: lets's begin our wonderful DPH206 this semester! :shipit: :rabbit: :rabbit2: :dog: :dog2:

**Comment by Wanqi-Wang** [comment]
:whale: :whale2:

**Comment by Wanqi-Wang** [comment]
Look it is a mountain railway: :mountain_railway: 
Look it is a (two) mag: :mag: :mag_right:
Look it is sun rise in morning:  :sunrise:

There is much more emoji than wechat

**Comment by Bella-yijing** [comment]
@Wanqi-Wang 
How could I type the emoticons? Where should I click?
