### ISSUE TITLE
How to change font size

### ISSUE THREAD

**Issue by Wanqi-Wang** [pzhaonet/dph206-2020#8]
I want to increase the font size of a word in the sentence (it's not in code) in R markdown, what should I do?

Also, how to do such in GitHub?

Thanks!!!

**Comment by pzhaonet** [comment]
It is NOT the markdown philosophy. You might use HTML, but I would not recommend it. 

Use markdown as simple as possible. Most times changing the size of a single word is unnecessary.

**Comment by Wanqi-Wang** [comment]
Thanks, Dr. Zhao, so how to change it in R studio, I cannot find a way too 😿

**Comment by pzhaonet** [comment]
Me neither.

**Comment by Wanqi-Wang** [comment]
Thank you!
